version: 2.1
orbs:
  node: circleci/node@5
  evals: circleci/evals@2.0
jobs:
  build-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts
            2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: "#e.g. ./deploy.sh"
      - run:
          name: found github actions config
          command: ":"
      - run:
          name: found jenkins config
          command: ":"
  evals-test-assertions-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - evals/test:
          assertions: assertions.json
          metrics: eval_results.json
          results: test_results.xml
workflows:
  build:
    jobs:
      - build-node:
          context:
            - Gemini-harshakumara1998030944@gmail.com
            - Pinecone-portfolio
            - LangSmith-portfolio
  test-eval-workflow:
    jobs:
      - evals-test-assertions-job
